#!/usr/bin/env python3
"""
Compare R1_T05 (joint best-step exact) vs R1_T06.1 (dense-format global exact).

This script reads CSV traces and T05 pickle result, then outputs a Markdown report
with quantitative evidence across four required dimensions:
1) Action target distribution
2) Step-wise lethality
3) Search-space advantage
4) Dense-format semantic loophole
"""

from __future__ import annotations

import argparse
import pickle
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd


# NOTE:
# T05 pickle was generated by a script run as __main__, so unpickling requires
# compatible class names in __main__.
@dataclass
class AttackStepLog:
    step: int = 0
    physical_flips_used: int = 0
    action_type: str = ""
    cost: int = 0
    layer_name: str = ""
    proxy_score_norm: float = 0.0
    exact_delta: float = 0.0
    exact_delta_norm: float = 0.0
    accuracy: float = 0.0
    loss: float = 0.0
    description: str = ""
    candidates_total_by_type: Dict[str, int] = field(default_factory=dict)
    candidates_topk_by_type: Dict[str, int] = field(default_factory=dict)


@dataclass
class UnifiedCandidate:
    action_type: str = ""
    score_proxy: float = 0.0
    score_proxy_norm: float = 0.0
    layer_name: str = ""
    cost: int = 1


def first_step_leq(values: List[float], threshold: float) -> Optional[int]:
    """Return first 1-based step index where value <= threshold. values[0] is baseline."""
    for i, v in enumerate(values):
        if i == 0:
            continue
        if v <= threshold:
            return i
    return None


def fmt_pct(x: float, ndigits: int = 2) -> str:
    return f"{x:.{ndigits}f}%"


def fmt_float(x: float, ndigits: int = 6) -> str:
    return f"{x:.{ndigits}f}"


def load_t05_result(path: Path) -> Dict[str, Any]:
    with path.open("rb") as f:
        data = pickle.load(f)
    if not isinstance(data, dict):
        raise TypeError(f"Unexpected T05 result type: {type(data)}")
    return data


def build_report(
    t06_global_csv: Path,
    t06_zero_csv: Path,
    t06_nonzero_csv: Path,
    t06_summary_csv: Path,
    t05_result_pkl: Path,
    t05_table_csv: Path,
) -> str:
    # Load T06 traces/summary
    g = pd.read_csv(t06_global_csv)
    z = pd.read_csv(t06_zero_csv)
    n = pd.read_csv(t06_nonzero_csv)
    s = pd.read_csv(t06_summary_csv)

    # Load T05 result
    t05 = load_t05_result(t05_result_pkl)
    t05_steps: List[AttackStepLog] = t05["step_logs"]
    t05_acc_hist: List[float] = t05["accuracy_history_physical"]
    t05_loss_hist: List[float] = t05["loss_history_physical"]
    t05_action_breakdown: Dict[str, int] = t05["action_breakdown"]
    t05_topk = int(t05.get("top_k", 64))

    # ----------------------------
    # 1) Action target distribution
    # ----------------------------
    window_len = min(15, len(g))
    g15 = g.head(window_len)
    g15_zero = int((g15["old_int8"] == 0).sum())
    g15_nonzero = int((g15["old_int8"] != 0).sum())
    g15_zero_ratio = (g15_zero / window_len * 100.0) if window_len > 0 else 0.0

    z_zero_ratio = float((z["old_int8"] == 0).mean() * 100.0) if len(z) > 0 else 0.0
    n_zero_ratio = float((n["old_int8"] == 0).mean() * 100.0) if len(n) > 0 else 0.0

    # ----------------------------
    # 2) Step-wise lethality
    # ----------------------------
    # T06 uses per-step trace (no baseline row in CSV)
    t06_step_to_10 = int(g.loc[g["acc_eval"] <= 10.0, "step"].min()) if (g["acc_eval"] <= 10.0).any() else None
    t06_step_to_10_5 = int(g.loc[g["acc_eval"] <= 10.5, "step"].min()) if (g["acc_eval"] <= 10.5).any() else None
    t06_step_to_12 = int(g.loc[g["acc_eval"] <= 12.0, "step"].min()) if (g["acc_eval"] <= 12.0).any() else None

    # T05 has baseline at index 0 in history
    t05_step_to_10 = first_step_leq(t05_acc_hist, 10.0)
    t05_step_to_10_5 = first_step_leq(t05_acc_hist, 10.5)
    t05_step_to_12 = first_step_leq(t05_acc_hist, 12.0)

    t06_exact_cum5 = float(g.head(5)["exact_score"].sum())
    t05_exact_cum5 = float(sum(step.exact_delta for step in t05_steps[:5]))
    exact_cum5_ratio = (t06_exact_cum5 / t05_exact_cum5) if t05_exact_cum5 != 0 else float("nan")

    # ----------------------------
    # 3) Search-space advantage (data-driven)
    # ----------------------------
    step1_totals = t05_steps[0].candidates_total_by_type if t05_steps else {}
    step1_topk_mix = t05_steps[0].candidates_topk_by_type if t05_steps else {}
    step1_total_candidates = int(sum(step1_totals.values())) if step1_totals else 0
    step1_weight_share = (
        step1_totals.get("weight_bit", 0) / step1_total_candidates * 100.0
        if step1_total_candidates > 0
        else 0.0
    )

    mode_exact_stats = pd.DataFrame(
        [
            {
                "mode": "T06.1 global",
                "steps": len(g),
                "exact_mean": float(g["exact_score"].mean()) if len(g) else 0.0,
                "exact_max": float(g["exact_score"].max()) if len(g) else 0.0,
                "final_acc": float(g["acc_eval"].iloc[-1]) if len(g) else float("nan"),
            },
            {
                "mode": "T06.1 zero_only",
                "steps": len(z),
                "exact_mean": float(z["exact_score"].mean()) if len(z) else 0.0,
                "exact_max": float(z["exact_score"].max()) if len(z) else 0.0,
                "final_acc": float(z["acc_eval"].iloc[-1]) if len(z) else float("nan"),
            },
            {
                "mode": "T06.1 nonzero_only",
                "steps": len(n),
                "exact_mean": float(n["exact_score"].mean()) if len(n) else 0.0,
                "exact_max": float(n["exact_score"].max()) if len(n) else 0.0,
                "final_acc": float(n["acc_eval"].iloc[-1]) if len(n) else float("nan"),
            },
        ]
    )

    common_steps = min(5, len(g), len(z), len(n))
    step_comp_rows = []
    for step in range(1, common_steps + 1):
        step_comp_rows.append(
            {
                "step": step,
                "global_exact": float(g.loc[g["step"] == step, "exact_score"].iloc[0]),
                "zero_exact": float(z.loc[z["step"] == step, "exact_score"].iloc[0]),
                "nonzero_exact": float(n.loc[n["step"] == step, "exact_score"].iloc[0]),
            }
        )
    step_comp = pd.DataFrame(step_comp_rows)

    # ----------------------------
    # 4) Semantic loophole summary numbers
    # ----------------------------
    # Evidence from traces:
    # - zero_only strictly attacks old_int8==0 in dense-format run
    # - despite that, it still causes large degradation
    zero_loss_gain = float(z["L_eval"].iloc[-1] - s.loc[s["mode"] == "zero_only", "baseline_loss_eval"].iloc[0]) if len(z) else 0.0
    zero_acc_drop = float(
        s.loc[s["mode"] == "zero_only", "acc_drop"].iloc[0].replace("%", "")
    ) if (s["mode"] == "zero_only").any() else 0.0

    # Build markdown
    lines: List[str] = []
    lines.append("# R1_T05 vs R1_T06.1 Exact Verification 对比分析报告")
    lines.append("")
    lines.append("## 数据来源")
    lines.append(f"- `{t06_global_csv}`")
    lines.append(f"- `{t06_zero_csv}`")
    lines.append(f"- `{t06_nonzero_csv}`")
    lines.append(f"- `{t06_summary_csv}`")
    lines.append(f"- `{t05_result_pkl}`")
    lines.append(f"- `{t05_table_csv}`")
    lines.append("")
    lines.append("## 结论先行")
    lines.append(f"- 当前这批结果中，`R1_T06.1 global` 在 **第 {t06_step_to_10_5} 步达到 10.2%**（near-random），明显快于 `R1_T05` 在 **第 {t05_step_to_10} 步达到 9.96%**。")
    lines.append(f"- 前 5 步累计 `ΔL_exact`：T06.1 global={fmt_float(t06_exact_cum5, 6)}，T05={fmt_float(t05_exact_cum5, 6)}，T06.1 高 **{(exact_cum5_ratio - 1.0) * 100.0:.2f}%**。")
    lines.append("- 本次数据里，T06.1 global 前 6 步全部打在 `old_int8 != 0`；但 `zero_only` 轨迹证明“被剪枝后置零位点”一旦在 dense-format 中暴露，仍有显著破坏力。")
    lines.append("")
    lines.append("## 1) 动作落点分布比对 (Action Target Distribution)")
    lines.append("")
    lines.append("| 轨迹 | 分析步数 | old_int8==0 次数 | old_int8!=0 次数 | old_int8==0 占比 |")
    lines.append("|---|---:|---:|---:|---:|")
    lines.append(f"| T06.1 global (前15步窗口，实际仅{window_len}步) | {window_len} | {g15_zero} | {g15_nonzero} | {g15_zero_ratio:.2f}% |")
    lines.append(f"| T06.1 zero_only (全程) | {len(z)} | {int((z['old_int8']==0).sum())} | {int((z['old_int8']!=0).sum())} | {z_zero_ratio:.2f}% |")
    lines.append(f"| T06.1 nonzero_only (全程) | {len(n)} | {int((n['old_int8']==0).sum())} | {int((n['old_int8']!=0).sum())} | {n_zero_ratio:.2f}% |")
    lines.append(f"| T05 joint (历史日志) | 50 | N/A | N/A | action 全为 `weight_bit` ({t05_action_breakdown.get('weight_bit',0)}/50) |")
    lines.append("")
    lines.append("对比解释：")
    lines.append("- T06.1 global 在当前 run 中并没有优先选择 `old_int8==0` 位点（前 6 步全是非零）。")
    lines.append("- T05 历史结果 `50/50` 全是 `weight_bit`，且该任务语义限定在 sparse-gated 活跃权重域内搜索。")
    lines.append("")
    lines.append("## 2) 破坏力步效分析 (Step-wise Lethality)")
    lines.append("")
    lines.append("| 指标 | R1_T05 | R1_T06.1 global |")
    lines.append("|---|---:|---:|")
    lines.append(f"| 达到 acc<=10.5% 的步数 | {t05_step_to_10_5} | {t06_step_to_10_5} |")
    lines.append(f"| 达到 acc<=10.0% 的步数 | {t05_step_to_10} | {t06_step_to_10 if t06_step_to_10 is not None else '未在已记录步数内达到'} |")
    lines.append(f"| 第5步累计 `ΔL_exact` | {fmt_float(t05_exact_cum5, 6)} | {fmt_float(t06_exact_cum5, 6)} |")
    lines.append(f"| 第5步累计 `ΔL_exact` 比值 (T06.1/T05) | - | {exact_cum5_ratio:.4f}x |")
    lines.append("")
    lines.append("补充：T06.1 global 仅记录到 6 步，是因为脚本在 `acc<12%` 时提前停止；第 6 步 `acc_eval=10.20%`。")
    lines.append("")
    lines.append("## 3) 搜索空间的数学优势 (Search Space Advantage)")
    lines.append("")
    lines.append("### 3.1 T05 的候选池/Top-K 竞争（Step 1）")
    lines.append("")
    lines.append("| 指标 | 数值 |")
    lines.append("|---|---:|")
    lines.append(f"| Stage-A 候选总数 | {step1_total_candidates} |")
    lines.append(f"| weight_bit 候选数 | {step1_totals.get('weight_bit', 0)} ({step1_weight_share:.2f}%) |")
    lines.append(f"| index_1bit 候选数 | {step1_totals.get('index_1bit', 0)} |")
    lines.append(f"| bitmask_swap 候选数 | {step1_totals.get('bitmask_swap', 0)} |")
    lines.append(f"| Top-K 组成 (K={t05_topk}) | weight={step1_topk_mix.get('weight_bit', 0)}, index={step1_topk_mix.get('index_1bit', 0)}, bitmask={step1_topk_mix.get('bitmask_swap', 0)} |")
    lines.append("")
    lines.append("### 3.2 T06.1 三种模式的 exact 强度对比（来自 CSV）")
    lines.append("")
    lines.append("| 模式 | 步数 | mean(ΔL_exact) | max(ΔL_exact) | 最终 acc |")
    lines.append("|---|---:|---:|---:|---:|")
    for _, row in mode_exact_stats.iterrows():
        lines.append(
            f"| {row['mode']} | {int(row['steps'])} | {row['exact_mean']:.6f} | {row['exact_max']:.6f} | {row['final_acc']:.2f}% |"
        )
    lines.append("")
    lines.append("### 3.3 前5步逐步对比（同起点，不同模式各自贪心）")
    lines.append("")
    lines.append("| step | global ΔL_exact | zero_only ΔL_exact | nonzero_only ΔL_exact |")
    lines.append("|---:|---:|---:|---:|")
    for _, row in step_comp.iterrows():
        lines.append(
            f"| {int(row['step'])} | {row['global_exact']:.6f} | {row['zero_exact']:.6f} | {row['nonzero_exact']:.6f} |"
        )
    lines.append("")
    lines.append("数据解释：")
    lines.append("- 当前 run 中，global 的高破坏动作主要与 nonzero_only 通道同量级；zero_only 的单步 `ΔL_exact` 明显更小。")
    lines.append("- 但 zero_only 能独立将准确率打到 11.95%，说明 dense-format 暴露的“原0权重位点”不是死区，而是有效附加攻击面。")
    lines.append("")
    lines.append("## 4) 密集格式搜索的语义漏洞 (Semantic Loophole)")
    lines.append("")
    lines.append("结合本次 CSV 证据与 T06.1 机制，可得：")
    lines.append("1. `zero_only` 全程 `old_int8==0`（100%），却在 12 步内把 acc 从 92.40% 降到 11.95%，loss 显著上升。")
    lines.append("2. 这说明 dense-format 下，原本被 sparse mask 隐藏的连接一旦被翻成大幅值（如 64/-128），会直接进入前向传播并改变激活分布。")
    lines.append("3. 对已在稀疏拓扑上适配的模型来说，这等价于“向未训练过的路径注入强噪声权重”，会造成分布偏移和级联误差。")
    lines.append("")
    lines.append("量化支撑（zero_only）：")
    lines.append(f"- 最终 acc drop: {zero_acc_drop:.2f}%")
    lines.append(f"- `L_eval` 增量（末步 - baseline）: {zero_loss_gain:.6f}")
    lines.append("")
    lines.append("## 结语")
    lines.append("- 这组结果支持“在同为 Exact Verification 下，T06.1 比 T05 更快崩溃”的现象。")
    lines.append("- 但就当前 CSV 而言，T06.1 global 的快崩并非来自“前几步大量打 zero 位点”，而是来自更强的非零位点候选；zero 位点提供的是额外后备破坏通道。")

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze R1_T05 vs R1_T06.1 exact-attack traces")
    parser.add_argument(
        "--t06-dir",
        type=Path,
        default=Path("results/R1/R1_T06_1_legacy_dense_format_bfa_exact"),
    )
    parser.add_argument(
        "--t05-result-pkl",
        type=Path,
        default=Path("results/R1/R1_T05_joint_best_step_attack_result.pkl"),
    )
    parser.add_argument(
        "--t05-table-csv",
        type=Path,
        default=Path("results/R1/R1_T05_joint_best_step_attack_table.csv"),
    )
    parser.add_argument(
        "--out-md",
        type=Path,
        default=Path("results/R1/R1_T05_vs_R1_T06_1_exact_report.md"),
    )
    args = parser.parse_args()

    t06_global_csv = args.t06_dir / "R1_T06_1_task1_global_trace.csv"
    t06_zero_csv = args.t06_dir / "R1_T06_1_task2_zero_only_trace.csv"
    t06_nonzero_csv = args.t06_dir / "R1_T06_1_task3_nonzero_only_trace.csv"
    t06_summary_csv = args.t06_dir / "R1_T06_1_summary_table.csv"

    report = build_report(
        t06_global_csv=t06_global_csv,
        t06_zero_csv=t06_zero_csv,
        t06_nonzero_csv=t06_nonzero_csv,
        t06_summary_csv=t06_summary_csv,
        t05_result_pkl=args.t05_result_pkl,
        t05_table_csv=args.t05_table_csv,
    )

    args.out_md.parent.mkdir(parents=True, exist_ok=True)
    args.out_md.write_text(report, encoding="utf-8")
    print(report)
    print(f"[Output] Saved report to {args.out_md}")


if __name__ == "__main__":
    main()

